Belphemur/SoundSwitch

.gitignore, SoundSwitch/Framework/Configuration/ISoundSwitchConfiguration.cs, SoundSwitch/Framework/Configuration/SoundSwitchConfiguration.cs, SoundSwitch/Model/AppModel.cs, SoundSwitch/Model/IAppModel.cs, SoundSwitch/SoundSwitch.csproj, SoundSwitch/UI/Forms/Settings.Designer.cs, SoundSwitch/UI/Forms/Settings.cs, SoundSwitch/UI/Forms/Settings.resx, SoundSwitch/Util/TrayIcon.cs
Add checkbox to enable/disable display of notifications. The sound that occurred with the notifications on Win10 was quite distracting.
=> Allow enable/disable display of notifications

README.md
To thanks jetbrain for their licence.
=> Add thanks category

SoundSwitch.UI.UserControls/TextProgressBar.cs
=> Fixed a crash which happened if the user disabled visual styles e.g. with the 'Windows Classic' theme of Windows 7.

Installer/scripts/products/vcredist2017.iss, Installer/scripts/products/vcredistversion.iss, Installer/setup.iss
Fix the detection of the build number
Add the new links to download the 2017 VC Redist
Make the 2017 VC redist a dependency
Fixes #203 
Fixes #200
=> Add VC Redist 2017 as dependency

SoundSwitch/Localization/AboutStrings.es.resx, SoundSwitch/Localization/Language.cs, SoundSwitch/Localization/LanguageParser.cs, SoundSwitch/Localization/SettingsStrings.es.resx, SoundSwitch/Localization/TrayIconStrings.es.resx, SoundSwitch/Localization/UpdateDownloadStrings.es.resx, SoundSwitch/SoundSwitch.csproj
Hello,
I added the spanish resources for SoundSwitch. I hope this can expand the use in Spanish language users. Best Regards
=> Spanish language added

Installer/scripts/products.iss, Installer/setup.iss, README.md
Hi, 
- I added an additional contribution to the implementation of Spanish language (Installer).
- Also, a bit bug with the wiki url
Best Regards
=> Added Spanish language in installer

Installer/scripts/products.iss
Add all idp languages available
Add Italian strings
Fix a Spanish string show as English.
=> Several updates

Installer/setup.iss
Update the Italian strings
Fix the problem about"Support the project" untranslated string.
=> Update Italian strings

README.de.md
Most of the content should be fine, I will adjust some little parts here and there on the weekend.
Requires changes on the installer script to be included in future releases.
Closes #366.
Thanks @Overload86 !
=> Added german README, based on translations from Overload86

README.de.md, README.md
The top-level section "Profiles" do not need a emoji, as too much are confusing.
=> Improved English readme and synced with German

SoundSwitch/UI/Forms/UpsertProfileExtended.Designer.cs
=> Re-organize controls of the profile form

README.de.md, README.md
=> chore(Readme): No more runtime to download

SoundSwitch/Framework/Audio/Lister/CachedAudioDeviceLister.cs
=> fix(Device): Listing device causing application hanging

SoundSwitch.UI.Menu/Form/QuickMenu.cs
Fix QuickMenu going off-screen
=> fix(QuickMenu): Take into account the edge of the screen and show the quick menu properly

SoundSwitch/UI/Forms/Settings.Designer.cs
Noticed items inside the Profiles tab were unadjusted
=> fix(profiles): Readjusted items in Profiles tab

.github/workflows/qodana.yml, qodana.yml
Switching to the native mode will solve false positives like [QD-8749](https://youtrack.jetbrains.com/issue/QD-8749)
=> Switch Qodana to the native mode

SoundSwitch/Framework/WinApi/Keyboard/HotKey.cs
UI is weird when you add some single keys, e.g. pause/break
=> Fix support for single key keybind

Installer/setup.iss
=> feat(cli): Add the CLI to windows PATH

SoundSwitch/UI/Component/TrayIcon.cs
Created a click timer to distinguish between single and double clicks properly.
=> fix: single and double click properly distinguished on tray icon

SoundSwitch/Framework/TrayIcon/IconDoubleClick/Action/IconDoubleClickSwitchProfile.cs, SoundSwitch/UI/Forms/Settings.Designer.cs, SoundSwitch/UI/Forms/Settings.cs
cleanup(settings): naming consistencies
=> cleanup(settings): naming consistencies
